<a href="https://colab.research.google.com/github/maverick98/CDS/blob/main/Mano_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [20]:
reviews=np.array(['nice food','amazing restaurant','too good','just loved it ','will go again','horrible food','never go there',
         'poor service','poor quality','needs improvement'])
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])


In [21]:
one_hot('nice food',500)

[325, 152]

In [22]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[22, 3],
 [11, 6],
 [23, 1],
 [27, 23, 7],
 [26, 29, 24],
 [26, 3],
 [28, 29, 18],
 [17, 22],
 [17, 1],
 [8, 13]]

In [23]:
max_length=3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
padded_reviews

array([[22,  3,  0],
       [11,  6,  0],
       [23,  1,  0],
       [27, 23,  7],
       [26, 29, 24],
       [26,  3,  0],
       [28, 29, 18],
       [17, 22,  0],
       [17,  1,  0],
       [ 8, 13,  0]], dtype=int32)

In [24]:
embedded_vector_size=4
model=Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation='softmax'))

In [25]:
X=padded_reviews
y=sentiment

In [26]:
type(X),type(y)

(numpy.ndarray, numpy.ndarray)

In [27]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics='accuracy')
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_2 (Flatten)         (None, 12)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.fit(X,y,epochs=50,verbose=1)

Epoch 1/50
1/1 [==============================] - 0s 7ms/step - loss: 0.6508 - accuracy: 0.5000
Epoch 2/50
1/1 [==============================] - 0s 11ms/step - loss: 0.6498 - accuracy: 0.5000
Epoch 3/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6487 - accuracy: 0.5000
Epoch 4/50
1/1 [==============================] - 0s 7ms/step - loss: 0.6477 - accuracy: 0.5000
Epoch 5/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6466 - accuracy: 0.5000
Epoch 6/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6456 - accuracy: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6445 - accuracy: 0.5000
Epoch 8/50
1/1 [==============================] - 0s 9ms/step - loss: 0.6434 - accuracy: 0.5000
Epoch 9/50
1/1 [==============================] - 0s 14ms/step - loss: 0.6423 - accuracy: 0.5000
Epoch 10/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6412 - accuracy: 0.5000
Epoch 11/50
1/1 [====================

In [30]:
loss,accuracy=model.evaluate(X,y)

1/1 [==============================] - 0s 116ms/step - loss: 0.5901 - accuracy: 0.5000


In [32]:
w= model.get_layer('embedding').get_weights()[0]

In [33]:
w.shape

(30, 4)

In [34]:
w

array([[-0.13133547, -0.1418903 ,  0.15780926,  0.09606059],
       [-0.04311099,  0.06793039,  0.08456603,  0.01475853],
       [-0.00652031,  0.00548106,  0.01587671,  0.0071613 ],
       [-0.0494345 ,  0.05373088,  0.02945036, -0.01207835],
       [-0.02250293, -0.0019855 , -0.04389826,  0.00033361],
       [-0.03626977, -0.01462107,  0.03231854, -0.02834734],
       [-0.12411834,  0.06293465,  0.07105608,  0.11593522],
       [ 0.08486505,  0.05938827, -0.07607222, -0.05371181],
       [ 0.06452999,  0.11132415,  0.11623827,  0.12491959],
       [-0.01866298,  0.04598905,  0.02937568,  0.02741287],
       [-0.00871216, -0.02527915,  0.0284082 ,  0.0244582 ],
       [-0.10744473, -0.12675364, -0.11649871, -0.15515079],
       [ 0.03969535,  0.00345206,  0.04788213,  0.0412018 ],
       [ 0.05193432, -0.11774468, -0.14376153, -0.07087089],
       [ 0.01489023,  0.01138628, -0.00873343, -0.0062135 ],
       [-0.04254736,  0.01276689,  0.00193463, -0.00690796],
       [-0.0421594 ,  0.

In [43]:
# 'nice food' paddings
padded_reviews[0]

array([22,  3,  0], dtype=int32)

In [40]:
#nice's embedding
w[padded_reviews[0][0]]

array([ 0.1026248 , -0.09563806, -0.08086336, -0.13280514], dtype=float32)

In [39]:
#Food's embedding
w[padded_reviews[0][1]]

array([ 0.1026248 , -0.09563806, -0.08086336, -0.13280514], dtype=float32)